### ISSUE TITLE
Build process for LLVM and terra

### ISSUE THREAD

**Issue by alexbw** [luapower/terra#2]
I've been poking around a bit to find the build process for LLVM, and then for Terra. Do you have it laid out anywhere for the both? I'm bumping up into all kinds of C++ linking errors, and was hoping to start from a build process that's already working before I branch out and try new things.

**Comment by capr** [comment]
The build scripts were only tested on the setup described here: https://luapower.com/building -- with anything else you're on your own :)

Once you have that, you can run the scripts directly from their own directory:

https://github.com/luapower/llvm/tree/master/csrc/llvm
https://github.com/luapower/terra/tree/master/csrc/terra

**Comment by alexbw** [comment]
Thanks!

**Comment by alexbw** [comment]
I'm having a bit of trouble tracing where exactly you do some custom commands defined in the terra `Makefile`, particularly where you run some equivalent of `luajit -bg terralib.lua terralib.h` and `lua genclangpaths.lua dummy.c clang $CUDA_INCLUDES`. Where should I be looking for the code that ends up invoking these?

**Comment by capr** [comment]
terralib.lua is not bundled, see https://luapower.com/terra
genclangpaths.lua is also not called (clang paths are not set, the idea being that the user does not need to have clang installed to run terra code)
